version: '3'
services:
  backend:
    image: 'maven:3-jdk-8'
    volumes:
     - ./parkinglot_back:/app/
    command: mvn spring-boot:run
    context: /app
    ports:
     - 8080:8080

  frontend:
    image: 'node:alpine-lts'
    volumes:
     - ./sites-enabled:/etc/nginx/sites-enabled/default
     - ./parkinglot_front:/app/
    ports:
     - 80:80

  front_builder:
    image: 'nginx:alpine'
    volumes:
     - ./parkinglot_front:/app/
    command: npm i && npm run build
    context: /app
