version: '3'
services:
  backend:
    image: 'maven:3-jdk-8-alpine'
    volumes:
     - ./parkinglot_back:/app/
    command: bash -c "
             apk add tzdata &&
             cp /usr/share/zoneinfo/America/Manaus /etc/localtime &&
             echo 'America/Manaus' > /etc/timezone &&
             mvn spring-boot:run
             "
    working_dir: /app
    ports:
     - 8080:8080

  frontend:
    image: 'nginx:alpine'
    volumes:
     - ./nginx.conf:/etc/nginx/conf.d/default.conf
     - ./parkinglot_front:/app/
    ports:
     - 80:80

  front_builder:
    image: 'node:lts-alpine'
    volumes:
     - ./parkinglot_front:/app/
    command: /bin/sh -c "npm i && npm run build"
    working_dir: /app
